### ISSUE TITLE
Can't compile librw

### ISSUE THREAD

**Issue by munemasaibuki** [Rinnegatamante/librw-vita#3]
Hello, I have installed vitasdk correctly on my windows 11 ubuntu subsystem, as well as getting premake5
But when I try to create a config with gmake it says : Error: /home/near/vdpm/librw-vita/premake5.lua:40: attempt to call global 'workspace' (a nil value)

Do you know why it fails? thanks

**Comment by Rinnegatamante** [comment]
just use "make".

**Comment by munemasaibuki** [comment]
Hello thanks for the fast reply, it worked fine

**Comment by Rinnegatamante** [comment]
install headers of the lib.

**Comment by munemasaibuki** [comment]
yes thank you it was my mistake, it all works fine now
